# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprestuser', '0002_personas_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='persona',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apprestuser.Personas'),
        ),
    ]
