# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprestuser', '0003_auto_20171104_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='apellidos',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personas',
            name='direccion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombres',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.TextField(max_length=10),
        ),
    ]
