# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprestuser', '0004_auto_20171104_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='apprestuser.Personas'),
        ),
    ]
